// 剧本相关类型定义

export interface Script {
  id: string;
  title: string;
  description?: string;
  outline?: string;
  worldSetting?: {
    era?: string;
    location?: string;
    main_characters?: string[];
    [key: string]: any;
  } | null;
  status: 'draft' | 'editing' | 'completed' | 'archived';
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string;
  tags?: ScriptTag[];
}

export interface ScriptTag {
  id: string;
  scriptId: string;
  tagName: string;
  color?: string | null;
  createdAt: string;
}

export interface CreateScriptParams {
  title: string;
  description?: string;
  outline?: string;
  tags?: string[];
  worldSetting?: {
    originalContent?: string;
    [key: string]: any;
  };
}

export interface UpdateScriptParams {
  title?: string;
  description?: string;
  outline?: string;
  tags?: string[];
}

